services:
  app:
    build:
      context: ./rest-input-adapter
      dockerfile: Dockerfile
    image: mi-spring-boot-app:latest
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      # Configuración de MongoDB
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mi_basedatos_mongo
      # Configuración de MariaDB
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/persona_db 
      SPRING_DATASOURCE_USERNAME: persona_db
      SPRING_DATASOURCE_PASSWORD: persona_db

      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongo
      - mariadb

  mongo:
    build:
      context: ./scripts/mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: persona_db
      MYSQL_USER: persona_db
      MYSQL_PASSWORD: persona_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./scripts/mariadb:/docker-entrypoint-initdb.d


volumes:
  mongo-data:
  mariadb-data:
